### ISSUE TITLE
test dataset construction

### ISSUE THREAD

**Issue by LeiyanGithub** [plageon/SlimPlm#1]
hello, your work is very inspiring and provides many insights. 

Regarding the experimental part, I would like to ask if the test dataset here is no taccording to the official version? Why would specific test_ids be given?

<img width="602" alt="image" src="https://github.com/plageon/SlimPlm/assets/45895439/d5636d52-4be2-418c-bd02-aa8b98347d75">

Your test dataset:
<img width="620" alt="image" src="https://github.com/plageon/SlimPlm/assets/45895439/26235789-3b01-498f-a3a4-f92afe216b99">

Official dataset:
<img width="241" alt="image" src="https://github.com/plageon/SlimPlm/assets/45895439/3d48cee4-162e-4cd7-91c5-0b76e496234d">

**Comment by plageon** [comment]
Thanks for following our work! 
Actually the test-ids provided is the index in the original dev or test dataset, where we sampled our test set. We have updated test-datasetid in the latest commit, https://github.com/plageon/SlimPlm/commit/7c581148165117b3f8da36c9b45f3a024e88aea8. The `id` field of the original dataset is provided. We hope this could solve your problem.

**Comment by LeiyanGithub** [comment]
Thank you for your knid response! I'm eager to follow your work, however, I noticed that the evaluation script in the readme.md is empty. Could you kindly provide it? Should I pursue your work in the future, I will be sure to cite your paper. Many thanks!
<img width="967" alt="image" src="https://github.com/plageon/SlimPlm/assets/45895439/d46019e3-66e4-465d-a0c7-f3b3e8f76e1c">

**Comment by plageon** [comment]
Thanks for your advice. We have revised the links provided in README.md. The link you have mentioned have been redirected to jupyter/evaluation_scripts.ipynb, https://github.com/plageon/SlimPlm/commit/c7fcd027baa218064f8a43ec657060f6e9f28c70.

**Comment by LeiyanGithub** [comment]
Thank you so much! Hello, I really like your job. May I ask if this paper has been applied to ACL or  NAACL?

**Comment by plageon** [comment]
> Thank you so much! Hello, I really like your job. May I ask if this paper has been applied to ACL or NAACL?

Thank you! It's currently under ARR February 2024 Cycle.
