### ISSUE TITLE
The input of the fine-tuned retrieval necessity judgment model

### ISSUE THREAD

**Issue by HCircle1997** [plageon/SlimPlm#2]
Hello! Your work is excellent!

May I ask what the input should be to directly use your fine-tuned retrieval necessity judgment model? This is because the prompt in the paper is not the same as the prompt in the hugging face example of get started, and prompt is not used in get started.

Looking forward to your reply!

**Comment by plageon** [comment]
It's suggested to follow the prompt format demonstrated in huggingface model repo.

**Comment by HCircle1997** [comment]
Huggingface model repo seems to only use **question**

**input_ids = tokenizer.encode(question, return_tensors="pt")**

Is that right?

**Comment by plageon** [comment]
`input_ids = tokenizer.encode(prompt.format(question=question, answer=heuristic_answer), return_tensors="pt")`
I made a mistake in the example inference code provided in hf model repo. Sorry for the confusion. 
I have updated the code in hf repo.

**Comment by HCircle1997** [comment]
Thank you so much for your prompt response and correction!
