### ISSUE TITLE
关于复现论文的一点疑问

### ISSUE THREAD

**Issue by yedeyang** [plageon/SlimPlm#4]
学长您好，我第一次尝试复现论文，请问如果仅想复现proxy model 和rewrite model推理的话，我该跑哪一段代码呢？谢谢！

**Comment by plageon** [comment]
Model Inference
Run chat inference for proxy language model or large language model, please refer to [chat_inference.sh](https://github.com/plageon/SlimPlm/blob/main/scripts/chat_inference.sh).

Run inference on the fine-tuned retrieval necessity judgment model or query rewriting model, please refer to [query_rewrite_inference.sh](https://github.com/plageon/SlimPlm/blob/main/scripts/query_rewrite_inference.sh).

**Comment by yedeyang** [comment]
我试图运行[query_rewrite_inference.sh]这个文件，出现了以下报错：File "./SlimPlm/user_intent/query_rewrite_inference.py", line 119, in <module>
    with open(input_file, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: './user_intent_data/asqa/llama7b/without_search/llama7b-asqa-test.jsonl'   

于是我查看了[query_rewrite_inference.py]     第110行有如下描述：input_file = f"./user_intent_data/{dataset}/{answer_model}/without_search/{answer_model}-{dataset}-{split}.jsonl" 然而实际上没有创建{answer_model}这个目录，请问这个问题该怎么解决呢？谢谢

**Comment by plageon** [comment]
在python代码添加创建目录的逻辑吧

**Comment by yedeyang** [comment]
好的，谢谢！
